before_script:
  - apt update
  - apt install -y build-essential cmake git rpm

build:ubuntu:16.04:
  stage: build
  image: ubuntu:16.04
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:16.04:
  stage: deploy
  dependencies:
    - build:ubuntu:16.04
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.a"
      - "build/*.so.*.*.*"

build:ubuntu:18.04:
  stage: build
  image: ubuntu:18.04
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:18.04:
  stage: deploy
  dependencies:
    - build:ubuntu:18.04
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.a"
      - "build/*.so.*.*.*"

build:ubuntu:19.04:
  stage: build
  image: ubuntu:19.04
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:19.04:
  stage: deploy
  dependencies:
    - build:ubuntu:19.04
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.a"
      - "build/*.so.*.*.*"