before_script:
  - apt update
  - apt install -y build-essential cmake file git rpm

build:debian:9:
  stage: build
  image: debian:9
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:debian:9:
  stage: deploy
  image: debian:9
  dependencies:
    - build:debian:9
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.a"
      - "build/*.so.*.*.*"

build:ubuntu:18.04:
  stage: build
  image: ubuntu:18.04
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:18.04:
  stage: deploy
  image: ubuntu:18.04
  dependencies:
    - build:ubuntu:18.04
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.a"
      - "build/*.so.*.*.*"

build:ubuntu:19.04:
  stage: build
  image: ubuntu:19.04
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:19.04:
  stage: deploy
  image: ubuntu:19.04
  dependencies:
    - build:ubuntu:19.04
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.a"
      - "build/*.so.*.*.*"

build:ubuntu:19.10:
  stage: build
  image: ubuntu:19.10
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:19.10:
  stage: deploy
  image: ubuntu:19.10
  dependencies:
    - build:ubuntu:19.10
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/*.a"
      - "build/*.so.*.*.*"